services:
  telegram-bot:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: ${APP_ENV}
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "9229:9229"
    environment:
      - NODE_ENV=${NODE_ENV}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - APP_PORT=${APP_PORT}
    volumes:
      - ./dist:/app/dist
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data: